### PR TITLE
Fix #60: Fix download notebook to server.

### LINKED ISSUE #60: Downloading gist to server fails
It returns a 403 when POSTing to the `/download_notebook` endpoint with the message:

```
403 POST /download_notebook (::1): '_xsrf' argument missing from POST  
```

### PR DESCRIPTION
**Pull request by mdboom**
Since 4.3.0, Jupyter requires that a xsrf token is passed with all requests
to the server.

This uses Jupyter's utils.ajax API call to make the request which is a thin
wrapper around jquery.ajax that handles the xsrf authentication.

Downside is that this change requires a minimum version of Jupyter notebook
of 4.3.1

### CODE REVIEW

**Comment by jezdez** [comment]
For the record, the utils.ajax function is defined here: https://github.com/jupyter/notebook/blob/e250b0b7bfb0b76100777f88953c717b45b31e98/notebook/static/base/js/utils.js#L788-L821

**Comment by jezdez** [comment]
@mdboom This looks wonderful, thanks!

File: src/jupyter_notebook_gist/static/extension.js [hunk 1]
```diff
@@ -109,33 +109,37 @@ define([
...
+                    "File already exists. Please enter a new name.\n" +
+                    "Note: This may overwrite existing files.",
+                    name);
                 if (newname == "" || newname == null) {
                     // prompt() returns "" if empty value, or null
                     // if user clicked cancel, want to abort in either case
                     return;
                 }
                 download_nb_on_server(url, newname, true);
             } else if (xhr.status == 200) {
```
Comment (jezdez) [inline src/jupyter_notebook_gist/static/extension.js]: @mdboom Oh wait, this handles a 200 response code, does that mean this should be handled by a `success` function callback instead of the `fail` you added?
